apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-sentinel
  labels:
    heritage: helm
spec:
  replicas: ${SENTINEL_REPLICAS}
  selector:
    redis-sentinel: "true"
  template:
    metadata:
      labels:
        name: redis-sentinel
        redis-sentinel: "true"
        role: sentinel
        provider: redis
    spec:
      nodeSelector:
        cluster: caas
      containers:
      - name: sentinel
        image: "hub.qingyuanos.com/redis:deis-v0.0.5"
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - containerPort: 26379
