#
# Redis configuration file for clustered mode
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster-config-${RELEASE_MARK}
data:
  redis.conf: |+
    cluster-enabled yes
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file nodes.conf
    cluster-migration-barrier 1
    appendonly yes
    # Other cluster members need to be able to connect
    protected-mode no
#
# A script to bootstrap PetSet members as they initialize
# TODO: Move this logic into a separate Docker image. We shouldn't be doing this kind of hackery here.
#
  bootstrap-pod.sh: |+
    #!/bin/sh
    set -e
    # Find which member of the PetSet this pod is running
    # e.g. "redis-cluster-0" -> "0"
    PET_ORDINAL=$(cat /etc/podinfo/pod_name | rev | cut -d- -f1)
    redis-server /conf/redis.conf &
    # TODO: Wait until redis-server process is ready
    sleep 1
    if [ $PET_ORDINAL = "0" ]; then
      # The first member of the cluster should control all slots initially
      redis-cli cluster addslots $(seq 0 16383)
    else
      # Other members of the cluster join as slaves
      # TODO: Get list of peers using the peer finder using an init container
      PEER_IP=$(perl -MSocket -e 'print inet_ntoa(scalar(gethostbyname("redis-cluster-${RELEASE_MARK}-0.redis-cluster-${RELEASE_MARK}.default.svc.cluster.local")))')
      redis-cli cluster meet $PEER_IP 6379
      sleep 1
      #echo redis-cli --csv cluster slots
      #redis-cli --csv cluster slots
      # Become the slave of a random master node
      MASTER_ID=$(redis-cli --csv cluster slots | cut -d, -f 5 | sed -e 's/^"//'  -e 's/"$//')
      redis-cli cluster replicate $MASTER_ID
    fi
    wait

