apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
  labels:
    heritage: helm
spec:
  replicas: ${REDIS_REPLICAS}
  selector:
    name: redis
  template:
    metadata:
      labels:
        app: redis-cluster
        name: redis
    spec:
      nodeSelector:
        cluster: caas
      containers:
      - name: redis
        image: "hub.qingyuanos.com/redis:deis-v0.0.5"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
        - name: data
          emptyDir: {}
