apiVersion: v1
kind: Service
metadata:
  labels:
    name: cassandra-${RELEASE_MARK}
  name: cassandra-${RELEASE_MARK}
spec:
  ports:
    - name: cassandra-port0
      port: 9042
      targetPort: 9042
  type: NodePort
  selector:
    name: cassandra-${RELEASE_MARK}
