apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: cassandra-${RELEASE_MARK}
  name: cassandra-${RELEASE_MARK}
spec:
  replicas: ${NODE_COUNT}
  selector:
    name: cassandra-${RELEASE_MARK}
  template:
    metadata:
      labels:
        name: cassandra-${RELEASE_MARK}
    spec:
      containers:
        - command:
            - /run.sh
          resources:
            limits:
              cpu: 0.1
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_SERVICE
              value: cassandra-${RELEASE_MARK}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: hub.qingyuanos.com/cassandra:v1
          name: cassandra
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: thrift
          volumeMounts:
            - mountPath: /cassandra_data
              name: data
      volumes:
        - name: data
          emptyDir: {}
