apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo-${RELEASE_MARK}
  name: mongo-${RELEASE_MARK}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo-${RELEASE_MARK}
    spec:
      containers:
      - image: hub.qingyuanos.com/mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          emptyDir: {}
