apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo-${RELEASE_MARK}
  name: mongo-${RELEASE_MARK}
spec:
  ports:
    - port: ${SERVICE_PORT}
      targetPort: 27017
      name: mongo-port-0
  type: NodePort
  selector:
    name: mongo-${RELEASE_MARK}
