apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mysql-${RELEASE_MARK}
  name: mysql-${RELEASE_MARK}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql-${RELEASE_MARK}
    spec:
      containers:
      - image: hub.qingyuanos.com/mysql
        name: mysql
        ports:
        - name: mysql
          containerPort: 3306
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: ${WP_PASSWORD}
        livenessProbe:
          tcpSocket:
            port: "mysql"
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command: ["mysqladmin", "status", "-p${WP_PASSWORD}"]
        volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          emptyDir: {}

