apiVersion: v1
kind: Service
metadata:
  labels:
    name: mysql-${RELEASE_MARK}
  name: mysql-${RELEASE_MARK}
spec:
  ports:
    - port: ${SERVICE_PORT}
      targetPort: 3306
      name: mysql-port-0
  type: NodePort
  selector:
    name: mysql-${RELEASE_MARK}
