apiVersion: v1
kind: Service
metadata:
  annotations:
    qingyuanos.io/service-catalog: 'github.com/qingyuancloud/kube-harpoon/wordpress/v1alpha'
    production: '{"vendor": "phpmyadmin.net", "docker": "https://github.com/phpmyadmin/docker"}'
  labels:
    app: wordpress
    heritage: qingyuancloud
  name: phpmyadmin-wordpress
  # namespace: harpoon
spec:
  ports:
  - port: 80
  selector:
    app: phpmyadmin
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    qingyuanos.io/service-catalog: 'github.com/qingyuancloud/kube-harpoon/wordpress/v1alpha'
    production: '{"vendor": "phpmyadmin.net", "docker": "https://github.com/phpmyadmin/docker"}'
  labels:
    app: wordpress
    heritage: qingyuancloud
  name: phpmyadmin-wordpress
  # namespace: harpoon
spec:
  replicas: 1
  selector:
    app: phpmyadmin
    tier: frontend
  template:
    metadata:
      labels:
        app: phpmyadmin
        tier: frontend
      name: phpmyadmin-wordpress
    spec:
      containers:
      - env:
        - name: PMA_HOST
          value: wordpress-mysql
        - name: PMA_PORT
          value: '3306'
        - name: PMA_USER
          value: root
        - name: PMA_PASSWORD
          value: password
        image: docker.io/phpmyadmin/phpmyadmin
        imagePullPolicy: IfNotPresent
        name: phpmyadmin-wordpress
        ports:
        - containerPort: 80
          name: phpmyadmin
