apiVersion: v1
kind: ReplicationController
metadata:
  name: rabbitmq-${RELEASE_MARK}
  labels:
    name: rabbitmq-${RELEASE_MARK}
    heritage: helm
spec:
  replicas: ${REPLICAS}
  template:
    metadata:
      labels:
        name: rabbitmq-${RELEASE_MARK}
    spec:
      containers:
      - name: rabbitmq
        image: hub.qingyuanos.com/rabbitmq:3.6.0
        ports:
        - containerPort: 5672
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
