apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-${RELEASE_MARK}
  labels:
    name: rabbitmq-${RELEASE_MARK}
    heritage: helm
spec:
  ports:
  - port: ${SERVICE_PORT}
    targetPort: 5672
  selector:
    name: rabbitmq-${RELEASE_MARK}
