kind: Service
apiVersion: v1
metadata:
  name: spark-master-${RELEASE_MARK}
  labels:
    heritage: helm
    provider: spark-${RELEASE_MARK}
spec:
  ports:
    - port: 7077
      targetPort: 7077
      name: port0
  type: NodePort
  selector:
    component: spark-master-${RELEASE_MARK}

