kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker-controller-${RELEASE_MARK}
  labels:
    heritage: helm
    provider: spark-${RELEASE_MARK}
spec:
  replicas: ${SPARK_WORKER_REPLICAS}
  selector:
    component: spark-worker-${RELEASE_MARK}
  template:
    metadata:
      labels:
        component: spark-worker-${RELEASE_MARK}
    spec:
      containers:
        - name: spark-worker
          image: hub.qingyuanos.com/spark:1.5.1_v3
          command: ["/start-worker"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m

