kind: Service
apiVersion: v1
metadata:
  name: spark-webui-${RELEASE_MARK}
  labels:
    heritage: helm
    provider: spark-${RELEASE_MARK}
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    component: spark-master-${RELEASE_MARK}
  type: LoadBalancer
