kind: Service
apiVersion: v1
metadata:
  name: zeppelin-${RELEASE_MARK}
  labels:
    heritage: helm
    provider: spark-${RELEASE_MARK}
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    component: zeppelin-${RELEASE_MARK}

