kind: ReplicationController
apiVersion: v1
metadata:
  name: zeppelin-controller-${RELEASE_MARK}
  labels:
    heritage: helm
    provider: spark-${RELEASE_MARK}
spec:
  replicas: 1
  selector:
    component: zeppelin-${RELEASE_MARK}
  template:
    metadata:
      labels:
        component: zeppelin-${RELEASE_MARK}
    spec:
      containers:
        - name: zeppelin
          image: hub.qingyuanos.com/zeppelin:v0.5.5_v2
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m

